name: Check pull request
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install --frozen-lockfile --non-interactive
      - name: TypeScript compiles
        run: yarn typescript
        if: ${{ always() }}
      - name: Linting checks are passed
        run: yarn lint
        if: ${{ always() }}
      - name: Test checks are passed
        run: yarn test --passWithNoTests
        if: ${{ always() }}
